---

- name: download JBoss AS tar for {{ jboss_version }}
  get_url: url={{ jboss_tar_url }}
           dest={{ jboss_tar_cache }}

- name: extract jboss tar
  unarchive: src={{ jboss_tar_cache }} dest={{ jboss_home_parent }}
             creates={{ jboss_home }}/jboss-modules.jar
             copy=no 
  notify: chown jboss_home

- name: create /etc/jboss-as
  file: name=/etc/jboss-as state=directory
        mode=0555 owner=root group=root

- name: various folders owned by {{ jboss_user }}
  file: name={{ item }} state=directory
        mode=0777 owner={{ jboss_user }} group={{ jboss_user }}
  with_items:
    - "{{ jboss_pid_dir }}"
    - "{{ jboss_log_dir }}"

- name: init script and /etc/jboss-as/jboss-as.conf
  template: src=.{{ item }}.j2
            dest={{ item }}
            mode=0555 owner=root group=root
  with_items:
    - /etc/init.d/jboss-as-domain
    - /etc/jboss-as/jboss-as.conf
  notify: chown jboss_home
