---

- hosts: dcs
  become: yes
# switch this as needed
  become_user: root
  roles:
    - openjdk7
    - jboss_install
    - xmlsetup
    - dc

- hosts: nodes
  become: yes
  become_user: root
  roles:
    - openjdk7
    - jboss_install
    - hc
