---

- name: create {{ jboss_user }} group
  group: name={{ jboss_user }}

- name: create {{ jboss_user }}
  user: name={{ jboss_user }} comment="Jboss User"
        group={{ jboss_user }}
        createhome=no home={{ jboss_home }}
