---

- name: download {{ jboss_version }} tarball
  get_url:
    url: "{{ jboss_tar_url }}"
    dest: "{{ jboss_tar_cache }}"

- name: extract jboss tarball
  unarchive:
    src: "{{ jboss_tar_cache }}"
    dest: "{{ jboss_home_parent }}"
    creates: "{{ jboss_home }}/jboss-modules.jar"
    copy: no 
  notify: bounce jboss

- name: chown jboss_home on first extract
  shell: "chown -R {{ jboss_user }}:{{ jboss_user }} {{ jboss_home }} && touch {{jboss_home}}/.chowned"
  args:
    creates: "{{jboss_home}}/.chowned"
    warn: no

- name: create /etc/jboss-as
  file:
    name: /etc/jboss-as
    state: directory
    mode: 0555
    owner: root
    group: root

- name: various folders owned by {{ jboss_user }}
  file:
    name: "{{ item }}"
    state: directory
    mode: 0777
    owner: "{{ jboss_user }}"
    group: "{{ jboss_user }}"
  with_items:
    - "{{ jboss_pid_dir }}"
    - "{{ jboss_log_dir }}"

- name: initscript, JBOSS_HOME env, /etc/jboss-as/jboss-as.conf
  template:
    src: ".{{ item }}.j2"
    dest: "{{ item }}"
    mode: 0555
    owner: root
    group: root
  with_items:
    - /etc/profile.d/jboss_home.sh
    - /etc/jboss-as/jboss-as.conf
    - /etc/init.d/jboss-as-domain
  notify: bounce jboss
