---

# jboss install, accounts etc. taken care
# of by 'jboss_install' dependency

- name: jboss-as-domain initscript
  template: src=etc/init.d/jboss-as-domain.j2
            dest=/etc/init.d/jboss-as-domain
            mode=0555 owner=root group=root
  notify: bounce jboss

- name: TODO domain config
  debug: msg=Soon(TM)...

- name: enable jboss-as-domain service
  service: name=jboss-as-domain state=started enabled=yes
