---

- name: stop DC to work on host.xml
  service: name=jboss-as-domain state=stopped

- name: reset host.xml from host-master.xml
  copy: src={{ jboss_config_dir }}/host-master.xml
        dest={{ jboss_hostxml }}
        remote_src=yes
  become: yes
  become_user: "{{ jboss_user }}"

- name: set host name
  xml:
    file: "{{ jboss_hostxml }}"
    namespaces:
      t: "{{ jboss_hostxmlns }}"
    xpath: /t:host
    attribute: name
    value: "{{ ansible_hostname }}"

- name: set management ip
  xml:
    file: "{{ jboss_hostxml }}"
    namespaces:
      t: "{{ jboss_hostxmlns }}"
    xpath: /t:host/t:interfaces/t:interface[@name="management"]/t:inet-address
    attribute: value
    value: "{{ jboss_mgmt_ip }}"

- name: point jboss-cli to new mgmt ip
  xml:
    file: "{{ jboss_home }}/bin/jboss-cli.xml"
    namespaces:
      c: "{{ jboss_clins }}"
    xpath: /c:jboss-cli/c:default-controller
    set_children:
      - host: "{{ ansible_default_ipv4.address }}"

- name: populate mgmt-users.properties
  template:
    src: JBOSS_CONFIG_DIR/mgmt-users.properties.j2
    dest: "{{ jboss_config_dir }}/mgmt-users.properties"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0600

- name: start DC again
  service: name=jboss-as-domain state=started
