---

- name: TODO | figure out how to safely edit host.xml
  debug:
    msg: "Template in-place is Good Enough™ for inital build. UNSAFE for prod."

# If HC is running, replacing host.xml risks corrupting it.
# using template means we regenerate the whole file
# at least.
- name: template host.xml
  template:
    src: JBOSS_CONFIG_DIR/host-slave.xml.j2
    dest: "{{ jboss_config_dir }}/host.xml"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0600
  notify: bounce jboss

- name: enable jboss
  service:
    name: jboss-as-domain
    state: started
    enabled: yes
