---

- name: TODO | configure host.xml
  template:
    src: JBOSS_CONFIG_DIR/host-slave.xml.j2
    dest: "{{ jboss_config_dir }}/host.xml"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0600
