jboss_hostxml: "{{ jboss_config_dir }}/host.xml"

jboss_hostxmlns: "urn:jboss:domain:1.2"
jboss_clins: "urn:jboss:cli:1.0"

jboss_mgmt_ip: "{{ ansible_default_ipv4.address }}"

# NB: you need this to be the same across nodes,
# so set it in $inventory/group_vars/all
# 
# each dict maps to a line in mgmt-users.properties on the DC
# mgmt_users:
#   - username: clusteruser
#     password: clusterpass
#     realm:    ManagementRealm
